# Generated by Django 5.0.7 on 2024-08-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='place_name',
            field=models.CharField(max_length=255),
        ),
    ]
